version: "3.8"

services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

  mongodbcopy:
    image : mongo
    command: mongod --port 27018
    container_name: mongodbcopy
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./databasecopy:/data/db
    ports:
      - 27018:27018
    restart: unless-stopped